name: Build and Deploy the Rick and Morty Web
on:
  push:
    branches: [ 'deploy' ]

permissions:
  contents: read

jobs: 
  build:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: cd ./react-web
      - run: npm install
      - run: npm run build

      - run: cd ../terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve 











